export default {
	series: 'series',
	cooperation: 'cooperation',
	contract: 'contract',
	place: 'place',
	tale: 'tale',
	// -----------
	fermentation: 'fermentation',
	style: 'style',
	extract: 'extract',
	alcohol: 'alcohol',
	filtration: 'filtration',
	pasteurization: 'pasteurization',
	refermentation: 'refermentation',
	aged: 'aged',
	dryHopped: 'dryHopped',
	expirationDate: 'expirationDate',
	// -----------
	ingredients: 'ingredients',
	ingredientsList: 'ingredientsList',
	smokedMalt: 'smokedMalt',
	// -----------
	bitterness: 'bitterness',
	sweetness: 'sweetness',
	fullness: 'fullness',
	power: 'power',
	hoppyness: 'hoppyness',
	temperature: 'temperature',
	// -----------
	price: 'price',
};
